name: Fix
on: 
  push:
    paths:
      - 'sub/url2'
  workflow_dispatch:

jobs:
  re-job:
    name: Fix
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Timezone
      run: sudo timedatectl set-timezone 'Asia/Shanghai'
    - name: git init
      run: | 
         git config --local user.name "GitHub Actions"
         git config --local user.email "actions@github.com"
    - name: sed
      run: | 
        cd ./sub/
        sed -i 's/^[ \t]*//g' url2 #删除行头空格和tab，对齐行头
        sed -i '/^sub:/d' url2     #删除以sub:开头的行
        sed -i '/^$/d' url2        #删除空白行
        sed -i -r '/^\s*$/d' url2  #删除带有空格或制表符的空行
    - name: subconverter
      run: | 
        base64 ./sub/url2 > ./utils/subconverter/b64 -w 0
        ./utils/subconverter/subconverter -g --artifact "fix" && rm ./utils/subconverter/b64
        base64 -d ./utils/subconverter/fix > ./utils/rm/url && rm ./utils/subconverter/fix
    - name: remove & rename
      run: cd ./utils/rm/ && npm ci && npm start
    - name: sub/url2
      run: | 
        rm ./utils/rm/url
        mv ./utils/rm/out ./sub/url2
        cd ./sub/ && sort url2 -o url2 #排序url2
    - name: git push
      run: git pull origin main && git add . && git commit -m "$(date '+%Y.%m.%d %H:%M:%S') 节点入库" && git push origin main
